"""added questions

Revision ID: 5bd39dce3693
Revises: 78fe3739700f
Create Date: 2020-07-04 13:23:44.535687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd39dce3693'
down_revision = '78fe3739700f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('_pickled_options', sa.PickleType(), nullable=True),
    sa.Column('index_correct', sa.Integer(), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_free'), 'question', ['free'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_free'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
